testname: Style Transfer MUSHRA Test
testId: style_transfer
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:
    # Generic welcome page
    # - type: generic
    #   id: first_page
    #   name: Welcome
    #   content: Welcome to webMUSHRA!
    # Consent page
    - type: consent
      id: consent_page
      name: Consent
      mustConsent: true
      content: >
          <p>The aim of this experiment is to assess the suitability of our deep-learning approach to audio production style matching using digital audio effects. In order to understand the perceptual performance of our model, we require human participants to listen to produced audio samples and give them a subjective rating.</p>
          <p>During this listening test you will be given a piece of reference audio and some style matching attempts (conditions). You will be asked to rate each of the conditions on a scale of 1-100, the rating should reflect your opinion of how well the condition matches the reference. Your answers will be stored in an anonymised format. If you exit the test before clicking the "Send Results" button, no information will be stored.</p>
          <p>If you have any questions, please feel free to email me at <a href="mailto:2357351g@student.gla.ac.uk">2357351g@student.gla.ac.uk</a>.</p>
          <p>Do you agree to taking part in this evaluation?</p>
    # Training page
    - type: mushra
      id: training
      name: MUSHRA
      content: >
        This training shows how to use the MUSHRA interface. Please perform the underlined instructions to proceed with the training session. 
        Reminder: In a MUSHRA listening test you are asked to rate the Basic Audio Quality (BAQ) of each condition.<br/>Basic Audio Quality is a single and global attribute that is used to judge any and all detected differences between the reference and the condition.
      showWaveform: true
      enableLooping: true 
      reference: configs/resources/audio/mono_ref.wav
      createAnchor35: true
      createAnchor70: true
      stimuli:
          C1: configs/resources/audio/mono_c1.wav
          C2: configs/resources/audio/mono_c2.wav
          C3: configs/resources/audio/mono_c3.wav
    - 
          - random

          # Compressor  
          - type: mushra
            id: multiband0
            name: MultiBand Compressor
            content: Please rate how well each condition matches the reference.
            enableLooping: true 
            reference: configs/resources/audio/y/multiband0.wav
            createAnchor35: false
            createAnchor70: false
            randomize: true
            stimuli:
                anchor: configs/resources/audio/rand_y_hat/multiband0.wav
                end2end: configs/resources/audio/e2e_y_hat/multiband0.wav
                style_transfer: configs/resources/audio/st_y_hat/multiband0.wav
          - type: mushra
            id: multiband1
            name: MultiBand Compressor
            content: Please rate how well each condition matches the reference.
            enableLooping: true 
            reference: configs/resources/audio/y/multiband1.wav
            createAnchor35: false
            createAnchor70: false
            randomize: true
            stimuli:
                anchor: configs/resources/audio/rand_y_hat/multiband1.wav
                end2end: configs/resources/audio/e2e_y_hat/multiband1.wav
                style_transfer: configs/resources/audio/st_y_hat/multiband1.wav    
          - type: mushra
            id: multiband2
            name: MultiBand Compressor
            content: Please rate how well each condition matches the reference.
            enableLooping: true 
            reference: configs/resources/audio/y/multiband2.wav
            createAnchor35: false
            createAnchor70: false
            randomize: true
            stimuli:
                anchor: configs/resources/audio/rand_y_hat/multiband2.wav
                end2end: configs/resources/audio/e2e_y_hat/multiband2.wav
                style_transfer: configs/resources/audio/st_y_hat/multiband2.wav   

          # Overdrive  
          - type: mushra
            id: overdrive0
            name: Overdrive/Distortion
            content: Please rate how well each condition matches the reference.
            enableLooping: true 
            reference: configs/resources/audio/y/overdrive0.wav
            createAnchor35: false
            createAnchor70: false
            randomize: true
            stimuli:
                anchor: configs/resources/audio/rand_y_hat/overdrive0.wav
                end2end: configs/resources/audio/e2e_y_hat/overdrive0.wav
          - type: mushra
            id: overdrive1
            name: Overdrive/Distortion
            content: Please rate how well each condition matches the reference.
            enableLooping: true 
            reference: configs/resources/audio/y/overdrive1.wav
            createAnchor35: false
            createAnchor70: false
            randomize: true
            stimuli:
                anchor: configs/resources/audio/rand_y_hat/overdrive1.wav
                end2end: configs/resources/audio/e2e_y_hat/overdrive1.wav
          - type: mushra
            id: overdrive2
            name: Overdrive/Distortion
            content: Please rate how well each condition matches the reference.
            enableLooping: true 
            reference: configs/resources/audio/y/overdrive2.wav
            createAnchor35: false
            createAnchor70: false
            randomize: true
            stimuli:
                anchor: configs/resources/audio/rand_y_hat/overdrive2.wav
                end2end: configs/resources/audio/e2e_y_hat/overdrive2.wav  

          # ambience  
          - type: mushra
            id: ambience0
            name: Reverb
            content: Please rate how well each condition matches the reference.
            enableLooping: true 
            reference: configs/resources/audio/y/ambience0.wav
            createAnchor35: false
            createAnchor70: false
            randomize: true
            stimuli:
                anchor: configs/resources/audio/rand_y_hat/ambience0.wav
                end2end: configs/resources/audio/e2e_y_hat/ambience0.wav
          - type: mushra
            id: ambience1
            name: Reverb
            content: Please rate how well each condition matches the reference.
            enableLooping: true 
            reference: configs/resources/audio/y/ambience1.wav
            createAnchor35: false
            createAnchor70: false
            randomize: true
            stimuli:
                anchor: configs/resources/audio/rand_y_hat/ambience1.wav
                end2end: configs/resources/audio/e2e_y_hat/ambience1.wav
          - type: mushra
            id: ambience2
            name: Reverb
            content: Please rate how well each condition matches the reference.
            enableLooping: true 
            reference: configs/resources/audio/y/ambience2.wav
            createAnchor35: false
            createAnchor70: false
            randomize: true
            stimuli:
                anchor: configs/resources/audio/rand_y_hat/ambience2.wav
                end2end: configs/resources/audio/e2e_y_hat/ambience2.wav  

          # delay  
          - type: mushra
            id: delay0
            name: Delay
            content: Please rate how well each condition matches the reference.
            enableLooping: true 
            reference: configs/resources/audio/y/delay0.wav
            createAnchor35: false
            createAnchor70: false
            randomize: true
            stimuli:
                anchor: configs/resources/audio/rand_y_hat/delay0.wav
                end2end: configs/resources/audio/e2e_y_hat/delay0.wav
          - type: mushra
            id: delay1
            name: Delay
            content: Please rate how well each condition matches the reference.
            enableLooping: true 
            reference: configs/resources/audio/y/delay1.wav
            createAnchor35: false
            createAnchor70: false
            randomize: true
            stimuli:
                anchor: configs/resources/audio/rand_y_hat/delay1.wav
                end2end: configs/resources/audio/e2e_y_hat/delay1.wav
          - type: mushra
            id: delay2
            name: Delay
            content: Please rate how well each condition matches the reference.
            enableLooping: true 
            reference: configs/resources/audio/y/delay2.wav
            createAnchor35: false
            createAnchor70: false
            randomize: true
            stimuli:
                anchor: configs/resources/audio/rand_y_hat/delay2.wav
                end2end: configs/resources/audio/e2e_y_hat/delay2.wav  

    - type: finish
      name: Thank you
      content: >
        <p>The main aim of this experiment was to investigate the performance of our deep-learning approach to audio production style matching using digital audio effects. Your ratings will help us gauge model performance against other style matching approaches.</p>
        <p>Thank you for your participation! Please remember to click the "Send Results" button for your responses to be logged.</p>
        <p>If you have any questions about this listening test, please feel free to email me at <a href="mailto:2357351g@student.gla.ac.uk">2357351g@student.gla.ac.uk</a>.</p>
      showResults: true
      writeResults: true
